#!/bin/bash

# Check if the required parameters are provided
if [ $# -ne 6 ]; then
    echo "Usage: $0 <cca> <predelay> <postdelay> <bandwidth> <buffer_size> <url>"
    exit 1
fi

# +----------------------------------------------+
# | Script to run simulation and process results |
# +----------------------------------------------+

# Set output directory for measurement results
output_dir="../measurements"

# Do you want to delete the original .pcap file after conversion?
delete_pcap_after_conversion=True

# Do you want to disable TCP SACK?
disable_SACK=False

# Assign input parameters to meaningful variable names
cca=$1
predelay=$2
postdelay=$3
bandwidth=$4
buffer_size=$5
url=$6

# The dump file is generated by the simulation
pcap_file="$output_dir/test.pcap"

# Kill any existing iperf, iperf3, tcpdump, and mm-delay processes
killall iperf iperf3 tcpdump mm-delay mm-link 2>/dev/null

# Create output directory if it doesn't exist
if [ ! -d "$output_dir" ]; then
    mkdir -p "$output_dir"
    echo "[run_test.sh] Folder '$output_dir' created."
else
    echo "[run_test.sh] Folder '$output_dir' already exists."
fi

# +-------------------------------------+
# | Run the simulation and capture data |
# +-------------------------------------+

# Disable TCP SACK if the parameter is True
if [ "$disable_SACK" == "True" ]; then
    sudo sh -c "echo '0' > /proc/sys/net/ipv4/tcp_sack"
fi

# Run the simulation
./simnet.sh "$cca" "$predelay" "$postdelay" "$bandwidth" "$buffer_size" "$url" "$pcap_file" "$output_dir"

# +-------------------------------------+
# | Convert received .pcap to .csv file |
# +-------------------------------------+

echo "[run_test.sh] Converting received data to .csv format"

# Create separate traces for TCP and UDP traffic
# Note: -o "gui.column.format:\"Time\",\"%Aut\"" is ommitted as it causes an error
tshark -r "$pcap_file" -T fields \
    -e _ws.col.cls_time \
    -e frame.time_relative \
    -e tcp.time_relative \
    -e frame.number \
    -e frame.len \
    -e ip.src \
    -e tcp.srcport \
    -e ip.dst \
    -e tcp.dstport \
    -e tcp.len \
    -e tcp.seq \
    -e tcp.ack \
    -E header=y \
    -E separator=, \
    -E quote=d \
    -E occurrence=f >"$output_dir/$cca-$predelay-$postdelay-$bandwidth-$buffer_size-tcp.csv"

# Capture UDP traffic
tshark -r "$pcap_file" -Y "udp" -E header=y -E separator=, -E quote=d >"$output_dir/$cca-udp.csv"

# Delete PCAP file if the parameter is True
if [ "$delete_pcap_file" == "True" ]; then
    rm "$pcap_file"
fi

# Log the completion of the conversion
echo "[run_test.sh] Conversion completed: $cca-$predelay-$postdelay-$bandwidth-$buffer_size-tcp.csv and $cca-$predelay-$postdelay-$bandwidth-$buffer_size-udp.csv generated."

# Remove residual index files
# rm -f index*

# Kill any remaining iperf, iperf3, tcpdump, and mm-delay processes
killall iperf iperf3 tcpdump mm-delay mm-link 2>/dev/null

# Completion message
echo "[run_test.sh] Test completed successfully."
